#!/usr/bin/env ruby
# frozen_string_literal: true

$LOAD_PATH.unshift File.join(File.dirname(__FILE__), "..", "lib")

require "contributor_covenant"

template_file = "./CONTRIBUTOR_COVENANT.md"

begin
  require template_file
  warn "=> Generating release notes..."
  ContributorCovenant.generate
  warn "=> Done!"
rescue SignalException => e
  # We might receive SIGTERM before our signal handler is installed.
  if Signal.signame(e.signo) == "TERM"
    exit(0)
  else
    raise
  end
rescue
  exit(1)
else
  exit(0)
end
